---
title: "Figure 3"
---

```{r}
source('source_file.R')
results = readxl::read_xlsx(paste0(tabdir, "Table 3.xlsx"))
```


```{r}
results$varorder = plyr::revalue(factor(results$variable), c(
     "Intercept" = "1", "Age" = "2", "Gender: Female" = "3", "Education" = "4",
     "Period: Wave 5" = "5", "Period: Wave 4" = "6", "Period: Wave 3" = "7",
     "Period: Wave 2" = "8", "System support" = "9", "Ideology: Far left" = "10",
     "Ideology: Center left" = "11", "Ideology: Center right" = "12",
     "Ideology: Far-right" = "13", "Socialization: After" = "14"
    ))
results$varorder = as.numeric(as.character(results$varorder))

results$lb = as.numeric(results$lb)
results$ub = as.numeric(results$ub)
results$coeff = (results$lb + results$ub) / 2 

results$model[results$icc == "4.093%"] = "Model 8: Pooled"

results$modelname = paste0(results$model, "\nICC = ", results$icc)
```

Coefficient plot:
```{r}
library(ggplot2)
results = results[order(results$varorder),]
varnames = unique(results$variable)

ggplot(data = results, aes(x = coeff, y = varorder)) + 
  geom_vline(xintercept = 0, color = "grey70", size = 0.5) + 
  geom_point(aes(x = coeff, y = varorder), size = 1) + 
  geom_segment(aes(x = lb, xend = ub, y = varorder, yend = varorder)) + 
  scale_y_continuous(breaks = c(1:(length(varnames))), labels = varnames) + 
  theme_minimal() + 
  theme(axis.title = element_blank(), 
        legend.position = "bottom", legend.title = element_blank(),
        panel.grid.minor.y = element_blank(), 
        strip.text = element_text(size = 10, lineheight = 1.5, vjust = 1) 
        ) +
  facet_wrap(. ~ modelname, nrow = 1)

ggsave(paste0(figdir, "Figure 3.png"), width = 14, height = 7)
```

